services:
  notation-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notation-server
    ports:
      - "4018:4018"
    environment:
      - PORT=4018
    volumes:
      - ./:/notation-server